// Goth / Industrial / Dark Alt Nights & Events (North America)
// Data compiled August 21 2025 (initial seed). Sources: official venue/event sites, Google business listings, event listings.
// Fields: id, nightName, theme, venueName, address, city, region, country, lat, lng, recurrence, scheduleDetail, notes, sources (array)
// DISCLAIMER: Recurrence & schedule can change; always verify via sources before traveling.
// ...existing code...
// --- Top 50 US Cities Batch 41–50 ---

// --- Top 50 US Cities Batch 41–50 ---
export const nights = [
  // ...existing entries...
  {
    id: 'va-virginia-beach-witching-hour',
    nightName: 'The Witching Hour',
    theme: 'Goth/Industrial',
    venueName: 'Brass Tap',
    address: '200 Monticello Ave, Williamsburg, VA 23185',
    city: 'Williamsburg',
    region: 'VA',
    country: 'US',
    lat: 37.2707,
    lng: -76.7075,
    type: 'club-night',
    recurrence: 'monthly',
    scheduleDetail: 'Third Tuesday, 9pm–1am',
    notes: 'Closest regular goth night to Virginia Beach. No cover.',
    sources: [
      'https://www.hardcorenorfolk.com/new-events/2021/10/19/the-witching-hour-goth-night',
      'https://www.reddit.com/r/VirginiaBeach/comments/167gmjh/goth_scene/'
    ]
  },
  {
    id: 'ca-oakland-hot-goth-night',
    nightName: 'Hot Goth Night',
    theme: 'Goth/Industrial/Darkwave',
    venueName: 'Thee Stork Club',
    address: '2330 Telegraph Ave, Oakland, CA 94612',
    city: 'Oakland',
    region: 'CA',
    country: 'US',
    lat: 37.8111,
    lng: -122.2687,
    type: 'club-night',
    recurrence: 'monthly',
    scheduleDetail: 'Saturday, monthly, 9pm–2am',
    notes: 'Features goth, industrial, darkwave, and kink performances.',
    sources: [
      'https://theestorkclub.com/',
      'https://www.instagram.com/p/DHYwhhxJopV/'
    ]
  },
  {
    id: 'mn-minneapolis-ground-zero',
    nightName: 'Bondage-A-Go-Go',
    theme: 'Goth/Industrial',
    venueName: 'Ground Zero Nightclub',
    address: '15 SE 4th St, Minneapolis, MN 55413',
    city: 'Minneapolis',
    region: 'MN',
    country: 'US',
    lat: 44.9872,
    lng: -93.2536,
    type: 'club-night',
    recurrence: 'weekly',
    scheduleDetail: 'Every Saturday, 10pm–2am',
    notes: 'Goth/industrial dance night with bondage shows.',
    sources: [
      'https://groundzeromn.com/schedule-events/',
      'https://www.reddit.com/r/goth/comments/1954e7q/a_goth_guide_to_minneapolisst_paul_minnesota/'
    ]
  },
  {
    id: 'ok-tulsa-starlite-goth-night',
    nightName: 'Goth Night',
    theme: 'Goth/Industrial',
    venueName: 'The Starlite Bar',
    address: '1902 E 11th St, Tulsa, OK 74104',
    city: 'Tulsa',
    region: 'OK',
    country: 'US',
    lat: 36.1456,
    lng: -95.9636,
    type: 'club-night',
    recurrence: 'weekly',
    scheduleDetail: 'Every Saturday, 9pm–2am',
    notes: 'Consistent goth night with live music.',
    sources: [
      'https://thestarlitebar.com/',
      'https://www.reddit.com/r/tulsa/comments/1f994ck/fellow_goth_ppl/'
    ]
  },
  {
    id: 'tx-arlington-sunshine-darkwave',
    nightName: 'Dark Wave/Goth Night',
    theme: 'Darkwave/Goth',
    venueName: 'Sunshine Bar',
    address: '902 W Division St, Arlington, TX 76012',
    city: 'Arlington',
    region: 'TX',
    country: 'US',
    lat: 32.7376,
    lng: -97.1131,
    type: 'club-night',
    recurrence: 'periodic',
    scheduleDetail: 'Check venue for schedule',
    notes: 'Periodic goth/darkwave events; check social media for dates.',
    sources: [
      'https://www.reddit.com/r/FortWorth/comments/15ycg42/where_to_find_an_active_goth_scene_in_fort_worth/'
    ]
  },
  {
    id: 'la-new-orleans-attrition',
    nightName: 'Attrition',
    theme: 'Goth/Industrial',
    venueName: 'The Goat',
    address: '1301 St Bernard Ave, New Orleans, LA 70116',
    city: 'New Orleans',
    region: 'LA',
    country: 'US',
    lat: 29.9742,
    lng: -90.0607,
    type: 'club-night',
    recurrence: 'monthly',
    scheduleDetail: 'Monthly, check venue for schedule',
    notes: 'Best-known goth/industrial night in New Orleans.',
    sources: [
      'https://www.facebook.com/attritionnola/',
      'https://www.thegoatneworleans.com/'
    ]
  },
  {
    id: 'ks-wichita-kirbys-goth-nite',
    nightName: 'Goth Nite',
    theme: 'Goth/Industrial',
    venueName: 'Kirby’s Beer Store',
    address: '3227 E 17th St N, Wichita, KS 67208',
    city: 'Wichita',
    region: 'KS',
    country: 'US',
    lat: 37.7042,
    lng: -97.2937,
    type: 'club-night',
    recurrence: 'monthly',
    scheduleDetail: 'Monthly, check venue for schedule',
    notes: 'Long-running goth night; check Facebook for dates.',
    sources: [
      'https://kirbysbeerstore.com/',
      'https://www.facebook.com/darkchurchentertainment/'
    ]
  },
  {
    id: 'oh-cleveland-nocturnal',
    nightName: 'Nocturnal',
    theme: 'Goth/Industrial/Darkwave',
    venueName: 'The Foundry Concert Club',
    address: '4256 Pearl Rd, Cleveland, OH 44109',
    city: 'Cleveland',
    region: 'OH',
    country: 'US',
    lat: 41.4372,
    lng: -81.7066,
    type: 'club-night',
    recurrence: 'monthly',
    scheduleDetail: 'Monthly, check venue for schedule',
    notes: 'Cleveland’s longest running goth night.',
    sources: [
      'https://www.facebook.com/GothicNation/',
      'https://www.instagram.com/nocturnalcleve/'
    ]
  },
  {
    id: 'fl-tampa-castle-midnight-mass',
    nightName: 'Midnight Mass',
    theme: 'Goth/Industrial/EBM',
    venueName: 'The Castle',
    address: '2004 N 16th St, Tampa, FL 33605',
    city: 'Tampa',
    region: 'FL',
    country: 'US',
    lat: 27.9632,
    lng: -82.4397,
    type: 'club-night',
    recurrence: 'weekly',
    scheduleDetail: 'Every Friday, 10:30pm–3am',
    notes: 'Legendary goth/industrial night; see also Absolution Fest (annual).',
    sources: [
      'https://castleybor.com/',
      'https://www.facebook.com/thecastleybor/'
    ]
  },
  {
    id: 'ca-bakersfield-club-abyss',
    nightName: 'Club Abyss',
    theme: 'Goth/Industrial/EBM/Darkwave',
    venueName: 'Jerry’s Pizza & Pub',
    address: '1817 Chester Ave, Bakersfield, CA 93301',
    city: 'Bakersfield',
    region: 'CA',
    country: 'US',
    lat: 35.3801,
    lng: -119.0195,
    type: 'club-night',
    recurrence: 'monthly',
    scheduleDetail: 'Monthly, check venue for schedule',
    notes: 'Goth/industrial/darkwave night; also hosts World Goth Day and Goth-O-Ween Fest.',
    sources: [
      'https://www.instagram.com/stagefrightclothing661/',
      'https://www.eventbrite.com/e/club-abyss-presents-world-goth-day-tickets-1360933993209'
    ]
  },
  {
    id: 'death-guild-sf',
    nightName: 'Death Guild',
    theme: 'Goth / Industrial dance night',
    venueName: 'DNA Lounge',
    address: '375 11th St',
    city: 'San Francisco',
    region: 'CA',
    country: 'US',
    lat: 37.7719,
    lng: -122.4129,
  type: 'club-night',
    recurrence: 'Weekly',
    scheduleDetail: 'Every Monday night (long-running since 1993).',
    notes: 'One of the longest running weekly goth/industrial nights in the U.S.',
    sources: ['https://www.dnalounge.com', 'https://deathguild.com']
  },
  {
    id: 'das-bunker-la',
    nightName: 'Das Bunker',
    theme: 'Multi-room Industrial / EBM / Dark Electronic',
    venueName: 'Catch One',
    address: '4067 W Pico Blvd',
    city: 'Los Angeles',
    region: 'CA',
    country: 'US',
    lat: 34.0479,
    lng: -118.3304,
  type: 'club-night',
    recurrence: 'Periodic',
    scheduleDetail: 'Large-scale themed events several times per year (anniversary, Summer Massive, special showcases).',
    notes: 'Historic LA industrial institution; not weekly—check site for next event.',
    sources: ['https://dasbunker.org', 'https://www.google.com/search?q=catch+one+das+bunker']
  },
  {
    id: 'bar-sinister-hollywood',
    nightName: 'Bar Sinister',
    theme: 'Goth / Industrial / Fetish-friendly alt',
    venueName: "Boardner's (Bar Sinister)",
    address: '1652 N Cherokee Ave',
    city: 'Hollywood',
    region: 'CA',
    country: 'US',
    lat: 34.1012773,
    lng: -118.3347367,
  type: 'club-night',
    recurrence: 'Weekly',
    scheduleDetail: 'Saturdays',
    notes: 'Established Saturday destination with live performances + DJs.',
    sources: ['https://barsinister.net', 'https://boardners.com']
  },
  {
    id: 'release-the-bats-long-beach',
    nightName: 'Release the Bats',
    theme: 'Deathrock / Goth / Post-Punk',
    venueName: 'Que Sera (historical; verify current venue)',
    address: '1923 E 7th St',
    city: 'Long Beach',
    region: 'CA',
    country: 'US',
    lat: 33.7754,
    lng: -118.1681,
  type: 'club-night',
    recurrence: 'Monthly',
    scheduleDetail: 'Historically 4th Friday (verify current schedule).',
    notes: 'Classic SoCal deathrock/goth night; venue or cadence may change—confirm before attending.',
    sources: ['https://releasethebats.com']
  },
  {
    id: 'qxts-newark',
    nightName: 'QXT\'s Alternative Nights',
    theme: 'Alternative / Goth / Industrial / New Wave',
    venueName: 'QXT\'s Night Club',
    address: '248 Mulberry St',
    city: 'Newark',
    region: 'NJ',
    country: 'US',
    lat: 40.7303241,
    lng: -74.1715361,
  type: 'club-night',
    recurrence: 'Multiple Weekly Themes',
    scheduleDetail: 'Open Wed–Sun with rotating themed goth/industrial/alt events; see public events page.',
    notes: 'Longest running alternative dance club in New Jersey.',
    sources: ['https://www.qxtsnightclub.com', 'https://www.google.com/search?q=qxts+newark+goth+night']
  },
  {
    id: 'elysium-haven-austin',
    nightName: 'Haven Goth Night',
    theme: 'Goth / Industrial / Darkwave',
    venueName: 'Elysium',
    address: '705 Red River St',
    city: 'Austin',
    region: 'TX',
    country: 'US',
    lat: 30.2669,
    lng: -97.7363,
  type: 'club-night',
    recurrence: 'Weekly',
    scheduleDetail: 'Typically Saturdays (Haven) + other themed goth/dark events—check calendar.',
    notes: 'Elysium hosts multiple dark alternative themed nights including Haven, World Goth Day events, etc.',
    sources: ['http://www.elysiumonline.net', 'https://www.google.com/search?q=elysium+austin+goth+night']
  },
  {
    id: 'mercury-machinewerks-seattle',
    nightName: 'Mercury @ MachineWerks Nights',
    theme: 'Private club – Gothic / Industrial / Electronic DJs',
    venueName: 'The Mercury @ MachineWerks',
    address: '1009 E Union St',
    city: 'Seattle',
    region: 'WA',
    country: 'US',
    lat: 47.6126,
    lng: -122.3187,
  type: 'club-night',
    recurrence: 'Multiple Weekly Nights',
    scheduleDetail: 'Open select nights weekly (membership or guest).',
    notes: 'Private membership club featuring goth/industrial/electronic DJs; schedule varies.',
    sources: ['https://www.google.com/search?q=mercury+at+machinewerks+seattle+goth']
  },
  {
    id: 'mechanismus-festival-seattle',
    nightName: 'Mechanismus Festival',
    theme: 'Industrial / Dark Electro / EBM multi-day festival',
    venueName: 'Multiple Seattle Venues',
    address: 'Seattle (various)',
    city: 'Seattle',
    region: 'WA',
    country: 'US',
    lat: 47.6086,
    lng: -122.3400,
  type: 'festival',
    recurrence: 'Annual',
    scheduleDetail: 'Annual multi-day festival (late spring / early summer; dates vary).',
    notes: 'Festival curated by Mechanismus promoting industrial and dark electronic artists.',
    sources: ['https://mechanismus.net', 'https://www.google.com/search?q=mechanismus+festival+seattle']
  },
  {
    id: 'dark-eighties-vancouver',
    nightName: 'The Dark Eighties',
    theme: 'Cult 80s / Goth / Darkwave / Synth / Post-Punk',
    venueName: 'Rotating Venues (Wise Hall, Biltmore, etc.)',
    address: '1882 Adanac St (Wise Hall example)',
    city: 'Vancouver',
    region: 'BC',
    country: 'CA',
    lat: 49.2760,
    lng: -123.0658,
  type: 'club-night',
    recurrence: 'Monthly / Touring',
    scheduleDetail: 'Recurring dance party; monthly in Vancouver plus touring dates in other cities.',
    notes: 'Check ticket platforms for next Vancouver date or touring stops.',
    sources: ['https://www.google.com/search?q=dark+eighties+vancouver']
  },
  {
    id: 'tokyo-nocturne-toronto',
    nightName: 'Tokyo Nocturne',
    theme: 'Visual Kei / J-Goth / J-Rock / Alternative Japanese subcultures',
    venueName: 'The Wych (event series venue)',
    address: '1150 Davenport Rd',
    city: 'Toronto',
    region: 'ON',
    country: 'CA',
    lat: 43.6769,
    lng: -79.4282,
  type: 'club-night',
    recurrence: 'Monthly',
    scheduleDetail: 'Monthly or periodic—verify upcoming date.',
    notes: 'Video dance party focusing on Visual Kei and related dark alternative Japanese genres.',
    sources: ['https://www.torontogothevents.com', 'https://www.google.com/search?q=goth+night+toronto+nocturne']
  }
  ,
  // --- Festivals & multi-day events (added Aug 2025) ---
  {
    id: 'dark-force-fest-2025',
    nightName: 'Dark Force Fest 2025',
    theme: 'Goth / Industrial / Darkwave / Post-Punk Multi-Day Festival',
    venueName: 'Sheraton Parsippany Hotel (full venue takeover)',
    address: '199 Smith Rd',
    city: 'Parsippany',
    region: 'NJ',
    country: 'US',
    lat: 40.8653,
    lng: -74.4254,
  type: 'festival',
    recurrence: 'Annual (Multi-Day)',
    scheduleDetail: 'May 2–4, 2025 (three-day hotel festival; check site for 2026 dates).',
    notes: 'Hotel takeover festival curated by VampireFreaks featuring ~35 bands, vendors, panels, late-night club events.',
    sources: ['https://darkforcefest.com', 'https://www.theaquarian.com/2025/04/21/spotlight-dark-force-fest-to-bring-goth-industrial-post-punk-to-parsippany/', 'https://www.atmostfear-entertainment.com/events/festivals/dark-force-fest-2025-vampirefreaks-goth-industrial-festival-grows-as-a-cultural-hub/']
  },
  {
    id: 'cold-waves-xiii-2025',
    nightName: 'Cold Waves XIII (Chicago 2025)',
    theme: 'Industrial / EBM / Dark Electronic Festival Series',
    venueName: 'Metro + Bottom Lounge + Gman Tavern',
    address: '3730 N Clark St (Metro primary)',
    city: 'Chicago',
    region: 'IL',
    country: 'US',
    lat: 41.9491,
    lng: -87.6557,
  type: 'festival',
    recurrence: 'Annual (Multi-Day, Multi-Venue)',
    scheduleDetail: 'September 24–28, 2025 (5 nights incl. kickoff & afterparties).',
    notes: 'Flagship Chicago edition of Cold Waves dark music festival; features legacy and contemporary industrial/EBM artists.',
    sources: ['https://www.coldwaves.net', 'https://www.google.com/search?q=cold+waves+2025+chicago+festival+dates']
  },
  {
    id: 'terminus-modulation-2025',
    nightName: 'Terminus: Modulation 2025',
    theme: 'Dark Electronic / Industrial / Synth / Post-Punk Festival',
    venueName: "Dickens (primary venue)",
    address: '1000 9 Ave SW (Dickens Pub)',
    city: 'Calgary',
    region: 'AB',
    country: 'CA',
    lat: 51.0447,
    lng: -114.0719,
  type: 'festival',
    recurrence: 'Annual (Multi-Day)',
    scheduleDetail: 'July 24–27, 2025 (weekend passes; multiple international acts).',
    notes: 'Established Canadian dark electronic & industrial festival hosting global lineup.',
    sources: ['https://terminus-festival.com', 'https://artoffact.com/news/front-line-assembly-dancing-plague-sacred-skin-the-foreign-resort-and-ghost-twin-announced-as-part-of-terminus-festival-2025/', 'https://www.google.com/search?q=Terminus+Festival+2025+Calgary+dates']
  },
  {
    id: 'convergence-27-2025',
    nightName: 'Convergence 27 (Denver 2025)',
    theme: 'Net.Goth Community Gathering / Goth Festival',
    venueName: 'HQ + Brown Palace (events & hotel)',
    address: '60 S Broadway (HQ Venue)',
    city: 'Denver',
    region: 'CO',
    country: 'US',
    lat: 39.7169,
    lng: -104.9870,
  type: 'festival',
    recurrence: 'Annual (Rotating City)',
    scheduleDetail: 'August 8–11, 2025 (multiple days; community-organized).',
    notes: 'Long-running North American goth gathering returning post-2020 hiatus; mix of shows, meetups, fashion & DJs.',
    sources: ['https://convergence27denver.com', 'https://www.google.com/search?q=Convergence+2025+Denver+goth+festival+dates']
  },
  {
    id: 'dark-castle-fest-2025',
    nightName: 'Dark Castle Fest 2025',
    theme: 'Gothic Music & Dark Arts Festival',
    venueName: 'Art Sanctuary',
    address: '1433 S Shelby St',
    city: 'Louisville',
    region: 'KY',
    country: 'US',
    lat: 38.2280,
    lng: -85.7355,
  type: 'festival',
    recurrence: 'Annual (Two-Day Halloween Weekend)',
    scheduleDetail: 'October 31 – November 1, 2025.',
    notes: 'Gothic music + dark arts marketplace curated by Radio Arcane; Halloween weekend edition.',
    sources: ['https://www.darkcastlefest.com', 'https://www.google.com/search?q=Dark+Castle+Fest+2025+dates+Louisville+Kentucky']
  },
  {
    id: 'murder-of-crows-2025',
    nightName: 'A Murder of Crows 2025',
    theme: 'Goth / Post-Punk Festival + Pre-Party',
    venueName: '(New York City venues – rotating)',
    address: 'Manhattan (see event site)',
    city: 'New York',
    region: 'NY',
    country: 'US',
    lat: 40.7580,
    lng: -73.9855,
  type: 'festival',
    recurrence: 'Annual (Late Summer)',
    scheduleDetail: 'Pre-party + main events August 29–30, 2025 (verify venues).',
    notes: 'Independent NYC goth & post-punk festival featuring international acts; includes pre-party night.',
    sources: ['https://brutalresonance.com/news/a-murder-of-crows-announces-nyc-gothic-post-punk-festival-for-august-2025/', 'https://www.google.com/search?q=a+murder+of+crows+festival+2025+nyc']
  },
  {
    id: 'glom-fest-2025',
    nightName: 'Glōm Fest 2025 (West Coast Tour)',
    theme: 'Darkwave / Goth / Deathrock Touring Micro-Festival',
    venueName: 'Multiple Cities (LA, SF, Portland, Vancouver)',
    address: 'Touring – see schedule',
    city: 'Los Angeles',
    region: 'CA',
    country: 'US',
    lat: 34.0522,
    lng: -118.2437,
  type: 'festival',
    recurrence: 'Inaugural / Touring (September 2025)',
    scheduleDetail: 'September 2025 West Coast dates (LA, SF, Portland, Vancouver).',
    notes: 'Multi-city traveling darkwave/deathrock lineup inaugural run; anchor marker placed at LA for mapping.',
    sources: ['https://post-punk.com/glom-fest-brings-darkwave-goth-and-deathrock-to-multiple-cities-on-the-west-coast-this-autumn/', 'https://www.google.com/search?q=glom+fest+2025']
  },
  {
    id: 'absolution-fest-2024',
    nightName: 'Absolution Fest 2024 (reference)',
    theme: 'Darkwave / Goth / Synth / Post-Punk Festival',
    venueName: 'The Orpheum',
    address: '14802 N Nebraska Ave',
    city: 'Tampa',
    region: 'FL',
    country: 'US',
    lat: 28.0796,
    lng: -82.4519,
  type: 'festival',
    recurrence: 'Annual (Fall)',
    scheduleDetail: 'Most recent past edition within last 12 months (verify 2025 announcement).',
    notes: 'Included as prior-year reference (within last 12 months) awaiting 2025 edition confirmation.',
    sources: ['https://www.google.com/search?q=absolution+fest+2024+tampa']
  },
  {
    id: 'gothic-cruise-2025',
    nightName: 'Gothic Cruise 2025',
    theme: 'At-Sea Goth / Industrial Music & Theme Cruise',
    venueName: 'Cruise Ship (Caribbean itinerary)',
    address: 'Port of Departure (varies)',
    city: 'Miami',
    region: 'FL',
    country: 'US',
    lat: 25.7781,
    lng: -80.1794,
  type: 'festival',
    recurrence: 'Annual (Cruise)',
    scheduleDetail: '2025 sailing dates TBD (recurring annual themed cruise; placeholder coordinates at Miami).',
    notes: 'Dark alternative themed cruise with live bands & DJs; placeholder until official 2025 port & dates confirmed.',
    sources: ['https://www.google.com/search?q=gothic+cruise+2025']
  }
  ,
  {
    id: 'colorado-goth-fest-2025',
    nightName: 'Colorado Goth Fest 2025 (10th Anniversary)',
    theme: 'Regional Goth / Post-Punk / Darkwave Festival',
    venueName: 'The Pearl (Formerly Mercury Cafe) + Related Denver Spaces',
    address: '2199 California St',
    city: 'Denver',
    region: 'CO',
    country: 'US',
    lat: 39.7526,
    lng: -104.9866,
  type: 'festival',
    recurrence: 'Annual (Early September)',
    scheduleDetail: 'September 5–6, 2025 core dates (10 Year Anniversary edition; multi-day programming & art show).',
    notes: 'Anniversary edition includes bands (e.g., Church Fire, Clockwork Echo, Cruel Mourning) and art components; verify final schedule & satellite events.',
    sources: ['https://tickets.holdmyticket.com/tickets/448630', 'https://www.facebook.com/ColoradoGothFest/']
  },
  {
    id: 'cruel-world-festival-2025',
    nightName: 'Cruel World Festival 2025',
    theme: 'Post-Punk / New Wave / Goth / Alt Rock Festival',
    venueName: 'Brookside at the Rose Bowl',
    address: '1001 Rose Bowl Dr',
    city: 'Pasadena',
    region: 'CA',
    country: 'US',
    lat: 34.1650,
    lng: -118.1670,
  type: 'festival',
    recurrence: 'Annual (May)',
    scheduleDetail: 'May 17, 2025 (single-day main festival – check site for future date announcements).',
    notes: 'Large-scale Goldenvoice-produced festival emphasizing legacy & contemporary post-punk, new wave and adjacent goth/alt acts.',
    sources: ['https://cruelworldfest.com', 'https://rosebowlstadium.com/events/details/482/cruel-world', 'https://www.musicfestivalwizard.com/festivals/cruel-world-festival-2025/']
  },
  {
    id: 'draculas-ball-philadelphia-2025',
    nightName: 'Dracula\'s Ball (Philadelphia)',
    theme: 'Goth / Industrial / Darkwave Special Event Series',
    venueName: 'Underground Arts (venue varies)',
    address: '1200 Callowhill St',
    city: 'Philadelphia',
    region: 'PA',
    country: 'US',
    lat: 39.9606,
    lng: -75.1599,
  type: 'festival',
    recurrence: 'Periodic (Holiday Weekends)',
    scheduleDetail: 'Major event nights (e.g., Halloween, Memorial Day, NYE) – verify next scheduled 2025/2026 date.',
    notes: 'Long-running Philadelphia gothic/industrial costume & performance event; venues have changed historically (Trocadero closed).',
    sources: ['https://www.google.com/search?q=draculas+ball+philadelphia+2025']
  },
  {
    id: 'endless-night-vampire-ball-nola-2025',
    nightName: 'Endless Night: New Orleans Vampire Ball 2025',
    theme: 'Goth / Vampire Subculture / Dark Masquerade',
    venueName: 'House of Blues New Orleans',
    address: '225 Decatur St',
    city: 'New Orleans',
    region: 'LA',
    country: 'US',
    lat: 29.9541,
    lng: -90.0659,
  type: 'festival',
    recurrence: 'Annual (Halloween Weekend)',
    scheduleDetail: 'Weekend event October 30 – Nov 2, 2025 (core Vampire Ball night Nov 1).',
    notes: 'Immersive themed ball + auxiliary salon and meet-up events; theme 2025 “Vampires of the Silver Screen.”',
    sources: ['https://endlessnightvampireball.com', 'https://www.eventbrite.com/e/2025-endless-night-new-orleans-vampire-ball-tickets-1069124442989', 'https://www.endlessnight.com']
  },
  {
    id: 'verboden-festival-2025',
    nightName: 'Verboden Festival 2025',
    theme: 'Darkwave / Post-Punk / Goth / Synth (Multi-Venue)',
    venueName: 'The Cobalt + Astoria + Additional Vancouver Venues',
    address: '917 Main St (The Cobalt)',
    city: 'Vancouver',
    region: 'BC',
    country: 'CA',
    lat: 49.2756,
    lng: -123.0999,
  type: 'festival',
    recurrence: 'Annual (May, Multi-Day)',
    scheduleDetail: 'May 8–11, 2025 (four nights, 40+ artists & DJs).',
    notes: 'Canada’s premier dedicated darkwave festival; multi-venue schedule with photo archives and nightly thematic curation.',
    sources: ['https://verbodenfestival.com', 'https://do604.com/events/2025/5/8/verboden-2025-tickets', 'https://www.todocanada.ca/city/vancouver/event/verboden-festival/']
  }
  ,
  // --- Added Top 10 US Cities batch (recurring club nights) Aug 21 2025 ---
  {
    id: 'red-party-nyc',
    nightName: 'The Red Party',
    theme: 'All Goth / Deathrock / Post-Punk Dance Night',
    venueName: 'Mercury Lounge (rotating special venues)',
    address: '217 E Houston St',
    city: 'New York',
    region: 'NY',
    country: 'US',
    lat: 40.7225,
    lng: -73.9871,
    type: 'club-night',
    recurrence: 'Monthly',
    scheduleDetail: '2nd Saturday (core cadence) – occasional special editions / festival tie-ins.',
    notes: 'Long-running NYC goth/post-punk/deathrock dance party (since 2007). Confirms monthly cadence via Instagram (2nd Saturdays). Venue can shift for special events.',
    sources: ['https://www.redpartynyc.com', 'https://www.instagram.com/redpartynyc/', 'https://www.reddit.com/r/goth/comments/1juq3lp/the_red_party_celebrates_18_years_of_goth_in_new/']
  },
  {
    id: 'bittersweet-late-bar-chicago',
    nightName: 'Bittersweet',
    theme: 'Monthly Goth / Post-Punk / New Wave Dance Night',
    venueName: 'Late Bar',
    address: '3534 W Belmont Ave',
    city: 'Chicago',
    region: 'IL',
    country: 'US',
    lat: 41.9399,
    lng: -87.7165,
    type: 'club-night',
    recurrence: 'Monthly',
    scheduleDetail: 'Last Friday of the month (10pm – late).',
    notes: 'Established monthly Chicago goth/post-punk dance night (est. 2010) with resident DJ Philly Peroxide; complements Cold Waves festival presence.',
    sources: ['https://do312.com/events/2025/8/29/bittersweet-monthly-goth-dance-night-tickets', 'http://latebarchicago.com', 'https://www.facebook.com/bittersweetchicago/']
  },
  {
    id: 'classic-numbers-houston',
    nightName: 'Classic Numbers',
    theme: 'Alternative / 80s / Goth / Industrial Video Night',
    venueName: 'Numbers Nightclub',
    address: '300 Westheimer Rd',
    city: 'Houston',
    region: 'TX',
    country: 'US',
    lat: 29.7447,
    lng: -95.3840,
    type: 'club-night',
    recurrence: 'Weekly',
    scheduleDetail: 'Every Friday (doors 9pm).',
    notes: 'Houston’s longest running weekly alternative/goth/industrial flavored dance & video night; active since late 1970s venue history.',
    sources: ['https://numbersnightclub.com', 'https://www.facebook.com/classicnumbers/', 'https://www.facebook.com/numbersnightclub/videos/classic-numbers-every-friday/1194759681971270/']
  },
  {
    id: 'six-feet-under-phoenix',
    nightName: '6 Feet Under',
    theme: 'Monthly Goth / Industrial Night',
    venueName: 'Club Palazzo',
    address: '710 N Central Ave',
    city: 'Phoenix',
    region: 'AZ',
    country: 'US',
    lat: 33.4554,
    lng: -112.0737,
    type: 'club-night',
    recurrence: 'Monthly',
    scheduleDetail: '2nd Friday (monthly) – large format event.',
    notes: 'Arizona dark underground monthly anchor event at historic Palazzo; pairs with weekly Communion at Stacy’s (not separately listed yet).',
    sources: ['https://6feetunderphx.com', 'https://www.facebook.com/6feetunderphx/', 'https://www.instagram.com/6feetunderphx/']
  },
  {
    id: 'vortex-philadelphia',
    nightName: 'VORTEX',
    theme: 'Goth / Industrial / Darkwave / EBM Club Night',
    venueName: 'Warehouse on Watts (Cambridge Hall)',
    address: '923 N Watts St',
    city: 'Philadelphia',
    region: 'PA',
    country: 'US',
    lat: 39.9697,
    lng: -75.1619,
    type: 'club-night',
    recurrence: 'Monthly',
    scheduleDetail: 'Monthly (dates vary; anniversary & themed editions).',
    notes: 'Long-running Philly goth/industrial/darkwave dance night (13+ years). Distinct from Dracula’s Ball (festival/holiday).',
    sources: ['https://wowphilly.com/vortex/', 'https://wowphilly.com/event/vortex-26/cambridge-hall/', 'https://phillygoth.net/']
  },
  {
    id: 'disorder-amp-room-san-antonio',
    nightName: 'Disorder',
    theme: 'New Wave / Dark Wave / Post-Punk / Goth Video Party',
    venueName: 'The Amp Room',
    address: '2407 N St Marys St',
    city: 'San Antonio',
    region: 'TX',
    country: 'US',
    lat: 29.4506,
    lng: -98.4862,
    type: 'club-night',
    recurrence: 'Periodic (Frequent)',
    scheduleDetail: 'Recurring (often monthly or more frequent) Saturday feature nights – verify next date.',
    notes: 'Promoted as dark wave/post-punk/goth video party by VJ/DJ organizers; schedule frequency can shift—verify current cadence.',
    sources: ['https://do210.com/events/weekly/thu/disorder-goth-new-wave-industrial', 'https://www.facebook.com/TheAmpRoom/', 'https://www.instagram.com/theamproom/']
  },
  {
    id: 'club-sabbat-san-diego',
    nightName: 'Club Sabbat',
    theme: 'Goth / Industrial / Fetish-friendly Dark Alternative Event',
    venueName: 'EQ San Diego (also Spin Nightclub for large editions)',
    address: '1271 University Ave',
    city: 'San Diego',
    region: 'CA',
    country: 'US',
    lat: 32.7496,
    lng: -117.1477,
    type: 'club-night',
    recurrence: 'Monthly / Special Editions',
    scheduleDetail: 'Core monthly events + anniversary & multi-level takeovers.',
    notes: 'Long-running San Diego gothic/industrial flagship (27+ years) with occasional larger multi-floor productions at Spin.',
    sources: ['https://www.eqsandiego.com/event/club-sabbat-9/', 'https://dosd.com/events/2025/8/9/club-sabbat-tickets', 'https://www.instagram.com/clubsabbat/']
  },
  {
    id: 'panoptikon-dallas',
    nightName: 'PANOPTIKON',
    theme: 'Industrial / Gothic / Darkwave / Synthpop / 80s Alternative',
    venueName: 'Sons of Hermann Hall',
    address: '3414 Elm St',
    city: 'Dallas',
    region: 'TX',
    country: 'US',
    lat: 32.7839,
    lng: -96.7765,
    type: 'club-night',
    recurrence: 'Weekly',
    scheduleDetail: 'Every Friday (18+ / 21+ pricing tiers).',
    notes: 'Weekly Dallas alternative dance institution since 2006; multi-genre dark electronic & 80s mix with resident DJs.',
    sources: ['https://www.instagram.com/panoptikondallas/', 'https://www.facebook.com/dallaspanoptikon', 'https://gothwiki.com/directory/panoptikon-industrial-discotheque/']
  },
  {
    id: 'resurgence-jacksonville',
    nightName: 'Resurgence Goth Night',
    theme: 'Goth / Industrial / Post-Punk / Darkwave DJs & Live Guests',
    venueName: 'The Albatross (Underbelly / Downtown events)',
    address: '113 E Bay St',
    city: 'Jacksonville',
    region: 'FL',
    country: 'US',
    lat: 30.3240,
    lng: -81.6557,
    type: 'club-night',
    recurrence: 'Monthly',
    scheduleDetail: 'Fourth Saturday (core cadence) – occasional special guest band editions.',
    notes: 'Monthly anchor for Jacksonville goth community with themed guest performances; all-ages or 18+ depending on edition.',
    sources: ['https://www.instagram.com/resurgencegothnight/', 'https://dtjax.com/events/vision-video-live-at-resurgence-goth-night-underbelly/', 'https://www.facebook.com/resurgencegothnight/']
  },
  // --- Added Top 20 US Cities batch (11–20) Aug 21 2025 ---
  {
    id: 'shrine-caravan-lounge-san-jose',
    nightName: 'Shrine',
    theme: 'Goth / Darkwave / Post-Punk / Industrial / Synth',
    venueName: 'The Caravan Lounge',
    address: '98 S Almaden Ave',
    city: 'San Jose',
    region: 'CA',
    country: 'US',
    lat: 37.3330,
    lng: -121.8931,
    type: 'club-night',
    recurrence: 'Monthly',
    scheduleDetail: 'Second Thursday monthly (9pm–1am, 21+)',
    notes: 'Long-running South Bay goth/dark alternative night with resident & guest DJs; multiple sources confirm second Thursday cadence.',
    sources: [
      'https://www.facebook.com/shrinesj',
      'https://www.instagram.com/shrinesanjose/',
      'https://www.sfgoth.com/bay-area-goth-calendar/'
    ]
  },
  {
    id: 'darkwave-dreams-hyde-park-san-jose',
    nightName: 'Darkwave Dreams',
    theme: 'Darkwave / Post-Punk / Dark Indie / Goth-Adjacent',
    venueName: 'Hyde Park Lounge',
    address: '1070 N 4th St',
    city: 'San Jose',
    region: 'CA',
    country: 'US',
    lat: 37.3455,
    lng: -121.8980,
    type: 'club-night',
    recurrence: 'Monthly',
    scheduleDetail: 'First Thursday monthly (9pm–1:30am, 21+)',
    notes: 'San Jose first-Thursday darkwave & post-punk DJ night at Hyde Park Lounge; complementary to Shrine (second Thursday).',
    sources: [
      'https://www.facebook.com/people/Darkwave-Dreams/100089421049085/',
      'https://m.facebook.com/events/226156823843286/',
      'https://www.yelp.com/biz/hyde-park-lounge-san-jose-3'
    ]
  }
  ,
  // --- Denver CO (Top 20 batch) Aug 21 2025 ---
  {
    id: 'goth-wednesdays-milk-bar-denver',
    nightName: 'Goth Wednesdays',
    theme: 'Goth / 80s / Alternative Multi-Room DJ Night',
    venueName: 'Milk Bar (SOCO District)',
    address: '1037 Broadway',
    city: 'Denver',
    region: 'CO',
    country: 'US',
    lat: 39.7315,
    lng: -104.9875,
    type: 'club-night',
    recurrence: 'Weekly',
    scheduleDetail: 'Every Wednesday (doors 9pm, 21+).',
    notes: 'Core weekly goth/alternative anchor night at Milk Bar (multi-room) per official venue schedule statement “Wednesdays - Goth / 80\'s / Alternative.”',
    sources: [
      'https://www.coclubs.com/venues/milk',
      'https://www.google.com/search?q=Milk+Bar+Denver+goth+industrial+night'
    ]
  },
  {
    id: 'deadbeat-saturdays-milk-bar-denver',
    nightName: 'DEADBEAT (Saturday Goth Floor)',
    theme: 'Exclusive Goth / Darkwave / Industrial Ritual (Milk Bar Floor)',
    venueName: 'Milk Bar (Alley Entrance)',
    address: '1037 Broadway',
    city: 'Denver',
    region: 'CO',
    country: 'US',
    lat: 39.7315,
    lng: -104.9875,
    type: 'club-night',
    recurrence: 'Weekly (Floor Programming)',
    scheduleDetail: 'Saturday nights – dedicated “Deadbeat” goth floor activation (check event calendar for special editions).',
    notes: 'Branded Saturday goth-focused floor (“Dance with us in the shadows at the newly summoned DEADBEAT floor — exclusive goth ritual”) within multi-format Saturday programming; treat as recurring floor identity.',
    sources: [
      'https://www.instagram.com/milkbardenver/',
      'https://www.google.com/search?q=Milk+Bar+Denver+goth+industrial+night',
      'https://www.coclubs.com/event-calendar'
    ]
  },
  {
    id: 'mixtape-3rd-saturdays-milk-bar-denver',
    nightName: 'MIXTAPE (3rd Saturdays)',
    theme: '80s Alternative / New Wave / Goth / Synthpop',
    venueName: 'Milk Bar (Polka Dot Room / Multi-Room)',
    address: '1037 Broadway',
    city: 'Denver',
    region: 'CO',
    country: 'US',
    lat: 39.7315,
    lng: -104.9875,
    type: 'club-night',
    recurrence: 'Monthly (3rd Saturday)',
    scheduleDetail: 'Third Saturday monthly core slot (resident DJ Slave1) — occasional schedule swaps noted.',
    notes: 'Recurring third Saturday alternative 80s / goth / new wave room identity at Milk; listing highlights dark alt crossover; schedule changes occasionally posted by DJs.',
    sources: [
      'https://www.google.com/search?q=Totenanz+Milk+Bar+Denver+3rd+Saturday',
      'https://www.facebook.com/djslave1/photos/just-a-heads-up-i-normally-dj-mixtape-at-milk-on-3rd-sats-but-i-swapped-my-weeke/10160856059502471/',
      'https://www.coclubs.com/venues/milk'
    ]
  },
  {
    id: 'dark-side-sundays-milk-bar-denver',
    nightName: 'Dark Side Sundays',
    theme: 'Dark Alternative / Goth / Industrial / Synthwave (Early Evening)',
    venueName: 'Milk Bar',
    address: '1037 Broadway',
    city: 'Denver',
    region: 'CO',
    country: 'US',
    lat: 39.7315,
    lng: -104.9875,
    type: 'club-night',
    recurrence: 'Weekly',
    scheduleDetail: 'Sundays – Dark Alternative format (recently adjusted hours e.g., 7pm–midnight per social posts).',
    notes: 'Sunday dark-alt programming block at Milk (“Dark Alternative format” with goth/industrial/synthwave emphasis); hours updated mid-2025 per staff/DJ posts.',
    sources: [
      'https://www.google.com/search?q=Milk+Bar+Denver+goth+industrial+night',
      'https://www.coclubs.com/venues/milk',
      'https://www.coclubs.com/event-calendar'
    ]
  }
    ,
    // --- New batch: Top 20 cities, Aug 2025 ---
    {
      id: 'sanctuary-myth-jacksonville',
      nightName: 'Sanctuary Goth Night',
      theme: 'Goth / Industrial / Darkwave DJs',
      venueName: 'Myth Nightclub',
      address: '333 E Bay St',
      city: 'Jacksonville',
      region: 'FL',
      country: 'US',
      lat: 30.3240,
      lng: -81.6557,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: '2nd Sunday monthly (18+).',
      notes: 'Jacksonville’s second monthly goth/industrial night; hosted at Myth Nightclub. Confirmed via Instagram and event listings.',
      sources: [
        'https://www.instagram.com/sanctuaryjax/',
        'https://www.etix.com/ticket/v/22144/myth-nightclub',
        'https://www.facebook.com/sanctuaryjax/'
      ]
    },
    {
      id: 'church-ace-of-cups-columbus',
      nightName: 'CHURCH (Ace of Cups)',
      theme: 'Goth / Industrial / Dark Alt Dance Night',
      venueName: 'Ace of Cups',
      address: '2619 N High St',
      city: 'Columbus',
      region: 'OH',
      country: 'US',
      lat: 40.0096,
      lng: -83.0096,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: '2nd Saturday monthly.',
      notes: 'CHURCH is Columbus’s anchor goth/industrial night, held at Ace of Cups on 2nd Saturdays. Confirmed via Instagram and venue calendar.',
      sources: [
        'https://www.facebook.com/gothchurch/',
        'https://www.instagram.com/cbusgoth/',
        'https://aceofcupsbar.com/'
      ]
    },
    {
      id: 'church-spacebar-columbus',
      nightName: 'CHURCH (Spacebar)',
      theme: 'Goth / Industrial / Dark Alt Dance Night',
      venueName: 'Spacebar',
      address: '2590 N High St',
      city: 'Columbus',
      region: 'OH',
      country: 'US',
      lat: 40.0102,
      lng: -83.0097,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: '4th Friday monthly.',
      notes: 'CHURCH brand’s second monthly event at Spacebar, Columbus. Confirmed via Instagram and venue posts.',
      sources: [
        'https://www.facebook.com/gothchurch/',
        'https://www.instagram.com/cbusgoth/',
        'https://www.facebook.com/spacebarcolumbus/'
      ]
    },
    {
      id: 'spellbound-indy-white-rabbit',
      nightName: 'Spellbound Indy',
      theme: 'Darkwave / Goth / Witchhouse / Dark Alt DJ Night',
      venueName: 'White Rabbit Cabaret',
      address: '1116 Prospect St',
      city: 'Indianapolis',
      region: 'IN',
      country: 'US',
      lat: 39.7521,
      lng: -86.1386,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Last Saturday monthly (21+).',
      notes: 'Spellbound is Indy’s long-running dark alternative DJ dance night, held at White Rabbit Cabaret. Confirmed via official site and venue calendar.',
      sources: [
        'https://www.spellboundindy.com/',
        'https://www.whiterabbitcabaret.com/spellbound',
        'https://www.eventbrite.com/o/spellbound-indy-31257368747',
        'https://www.instagram.com/spellboundindy/'
      ]
    },
    {
      id: 'requiem-tommys-pub-charlotte',
      nightName: 'Requiem',
      theme: 'Goth / Industrial / Dark Alt Dance Night',
      venueName: 'Tommy’s Pub',
      address: '3124 Eastway Dr',
      city: 'Charlotte',
      region: 'NC',
      country: 'US',
      lat: 35.2172,
      lng: -80.7827,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Typically 2nd or 3rd Saturday monthly (confirm via calendar).',
      notes: 'Charlotte’s main goth/industrial night, hosted at Tommy’s Pub. Confirmed via Instagram and local scene calendar.',
      sources: [
        'https://www.instagram.com/requiemgothnight/',
        'https://charlottedarkscene.com/',
        'https://www.facebook.com/events/tommys-pub/requiem/'
      ]
    },
    {
      id: 'kiss-kiss-bang-bang-dc',
      nightName: 'Kiss Kiss Bang Bang',
      theme: '80s Alternative / New Wave / Post-Punk / Goth',
      venueName: 'Little Miss Whiskeys',
      address: '1104 H St NE',
      city: 'Washington',
      region: 'DC',
      country: 'US',
      lat: 38.9007,
      lng: -76.9832,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: '4th Wednesday monthly (free admission, 2nd floor).',
      notes: 'Spellbound DC’s monthly offshoot, featuring classic 80s, post-punk, and goth. Confirmed via official site.',
      sources: [
        'https://www.spellbound-dc.com/events.html',
        'https://www.instagram.com/littlemisswhiskeys/'
      ]
    },
    {
      id: 'dark-sparkle-dna-sf',
      nightName: 'Dark Sparkle',
      theme: 'Goth / Darkwave / Post-Punk / Glam',
      venueName: 'DNA Lounge',
      address: '375 11th St',
      city: 'San Francisco',
      region: 'CA',
      country: 'US',
      lat: 37.7719,
      lng: -122.4129,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly Fridays (see DNA Lounge calendar for dates).',
      notes: 'Long-running monthly goth/darkwave night at DNA Lounge, SF. Confirmed via venue calendar and social media.',
      sources: [
        'https://www.dnalounge.com/calendar/',
        'https://www.instagram.com/mizmargo/',
        'https://www.facebook.com/dnalounge/'
      ]
    },
    {
      id: 'interzone-f8-sf',
      nightName: 'INTERZONE',
      theme: 'Darkwave / Goth / EBM / Industrial',
      venueName: 'F8',
      address: '1192 Folsom St',
      city: 'San Francisco',
      region: 'CA',
      country: 'US',
      lat: 37.7753,
      lng: -122.4101,
      type: 'club-night',
      recurrence: 'Weekly',
      scheduleDetail: 'Every Tuesday (free darkwave dance party).',
      notes: 'INTERZONE is a free weekly darkwave/goth/EBM/industrial party at F8, SF. Confirmed via venue calendar and social media.',
      sources: [
        'http://www.feightsf.com/new-events/interzone-sf-free-darkwave-dance-party-july-1-2025',
        'https://www.instagram.com/interzonesf/',
        'https://www.facebook.com/groups/californiagothevents/'
      ]
    },
    {
      id: 'goth-night-horus-hall-fort-worth',
      nightName: 'Goth Night',
      theme: 'Industrial / Post-Punk / Darkwave',
      venueName: 'Horus Hall',
      address: '100 E Exchange Ave',
      city: 'Fort Worth',
      region: 'TX',
      country: 'US',
      lat: 32.7876,
      lng: -97.3472,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Last weekend monthly (18+, no cover).',
      notes: 'Fort Worth’s recurring goth/industrial night at Horus Hall, Stockyards, with DJ Empty Channel. Confirmed via venue and event listings.',
      sources: [
        'https://www.fortworthstockyards.org/events/goth-night',
        'https://www.facebook.com/horushallfw/'
      ]
    },
    // --- Top 50 US Cities batch (31–40) Aug 2025 ---
    {
      id: 'goth-barge-milwaukee',
      nightName: 'Goth Barge',
      theme: 'Goth / Industrial / Darkwave River Party',
      venueName: 'Milwaukee River (various boats)',
      address: 'Milwaukee Riverwalk',
      city: 'Milwaukee',
      region: 'WI',
      country: 'US',
      lat: 43.0389,
      lng: -87.9065,
      type: 'club-night',
      recurrence: 'Monthly (Summer)',
      scheduleDetail: 'Monthly summer goth/industrial boat party (June–Sept).',
      notes: 'Unique summer goth/industrial event on Milwaukee River boats; check social for next sailing.',
      sources: [
        'https://www.facebook.com/gothbargemke/',
        'https://www.instagram.com/gothbargemke/'
      ]
    },
    {
      id: 'mad-planet-goth-night-milwaukee',
      nightName: 'Mad Planet Goth Night',
      theme: 'Goth / Industrial / Darkwave',
      venueName: 'Mad Planet',
      address: '533 E Center St',
      city: 'Milwaukee',
      region: 'WI',
      country: 'US',
      lat: 43.0671,
      lng: -87.8997,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly goth/industrial night (dates vary).',
      notes: 'Long-running Milwaukee goth/industrial night at Mad Planet; check calendar for next event.',
      sources: [
        'https://www.mad-planet.net/',
        'https://www.facebook.com/madplanetmke/'
      ]
    },
    {
      id: 'apparition-launchpad-albuquerque',
      nightName: 'Apparition',
      theme: 'Goth / Industrial / Darkwave',
      venueName: 'Launchpad',
      address: '618 Central Ave SW',
      city: 'Albuquerque',
      region: 'NM',
      country: 'US',
      lat: 35.0836,
      lng: -106.6504,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly goth/industrial night (dates vary).',
      notes: 'Apparition is Albuquerque’s anchor goth/industrial night at Launchpad; check social for next event.',
      sources: [
        'https://www.facebook.com/ApparitionABQ/',
        'https://www.launchpadrocks.com/'
      ]
    },
    {
      id: 'noche-gotica-latina-effex-abq',
      nightName: 'Noche Gotica Latina',
      theme: 'Latin Goth / Industrial / Darkwave',
      venueName: 'Effex Nightclub',
      address: '420 Central Ave SW',
      city: 'Albuquerque',
      region: 'NM',
      country: 'US',
      lat: 35.0841,
      lng: -106.6506,
      type: 'club-night',
      recurrence: 'Periodic',
      scheduleDetail: 'Periodic Latin goth/industrial night (dates vary).',
      notes: 'Latin-themed goth/industrial night at Effex; check social for next event.',
      sources: [
        'https://www.instagram.com/nochegoticalatina/',
        'https://www.facebook.com/EffexNightclub/'
      ]
    },
    {
      id: 'nm-goth-fest-albuquerque',
      nightName: 'NM Goth Fest',
      theme: 'Goth / Industrial / Darkwave Festival',
      venueName: 'Launchpad',
      address: '618 Central Ave SW',
      city: 'Albuquerque',
      region: 'NM',
      country: 'US',
      lat: 35.0836,
      lng: -106.6504,
      type: 'festival',
      recurrence: 'Annual',
      scheduleDetail: 'Annual multi-band goth/industrial festival (dates vary).',
      notes: 'Annual New Mexico goth/industrial festival at Launchpad; check site for next edition.',
      sources: [
        'https://www.facebook.com/NMGothFest/',
        'https://www.launchpadrocks.com/'
      ]
    },
    {
      id: 'queer-goth-nite-hotel-congress-tucson',
      nightName: 'Queer Goth Nite',
      theme: 'Queer Goth / Darkwave / Industrial',
      venueName: 'Hotel Congress',
      address: '311 E Congress St',
      city: 'Tucson',
      region: 'AZ',
      country: 'US',
      lat: 32.2226,
      lng: -110.9698,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly queer goth/industrial night (dates vary).',
      notes: 'Queer-focused goth/industrial night at Hotel Congress; check social for next event.',
      sources: [
        'https://www.instagram.com/queergothnite/',
        'https://hotelcongress.com/'
      ]
    },
    {
      id: 'unhappy-hour-surly-wench-tucson',
      nightName: 'Unhappy Hour',
      theme: 'Goth / Darkwave / Post-Punk',
      venueName: 'Surly Wench Pub',
      address: '424 N 4th Ave',
      city: 'Tucson',
      region: 'AZ',
      country: 'US',
      lat: 32.2287,
      lng: -110.9657,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly goth/darkwave night (dates vary).',
      notes: 'Unhappy Hour is Tucson’s long-running goth/darkwave night at Surly Wench Pub; check social for next event.',
      sources: [
        'https://www.facebook.com/UnhappyHourTucson/',
        'https://www.surlywench.com/'
      ]
    },
    {
      id: 'crimewave-strummers-fresno',
      nightName: 'CRIMEWAVE',
      theme: 'Goth / Industrial / Darkwave',
      venueName: 'Strummer’s',
      address: '833 E Fern Ave',
      city: 'Fresno',
      region: 'CA',
      country: 'US',
      lat: 36.7572,
      lng: -119.7714,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly goth/industrial night (dates vary).',
      notes: 'CRIMEWAVE is Fresno’s anchor goth/industrial night at Strummer’s; check social for next event.',
      sources: [
        'https://www.instagram.com/crimewaveparty/',
        'https://www.strummersclub.com/'
      ]
    },
    {
      id: 'disorder-presents-full-circle-fresno',
      nightName: 'Disorder Presents',
      theme: 'Goth / Post-Punk / Darkwave',
      venueName: 'Full Circle Brewing',
      address: '712 Fulton St',
      city: 'Fresno',
      region: 'CA',
      country: 'US',
      lat: 36.7366,
      lng: -119.7856,
      type: 'club-night',
      recurrence: 'Periodic',
      scheduleDetail: 'Periodic goth/post-punk/darkwave night (dates vary).',
      notes: 'Disorder Presents is a periodic goth/post-punk/darkwave event at Full Circle Brewing; check social for next event.',
      sources: [
        'https://www.instagram.com/disorderpresents/',
        'https://www.fullcirclebrewing.com/'
      ]
    },
    {
      id: 'bats-in-the-attic-chupacabra-mesa',
      nightName: 'Bats in the Attic',
      theme: 'Goth / Darkwave / Industrial',
      venueName: 'Chupacabra Taproom',
      address: '14 N Robson',
      city: 'Mesa',
      region: 'AZ',
      country: 'US',
      lat: 33.4152,
      lng: -111.8315,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly goth/darkwave night (dates vary).',
      notes: 'Bats in the Attic is Mesa’s anchor goth/darkwave night at Chupacabra Taproom; check social for next event.',
      sources: [
        'https://www.instagram.com/batsintheatticaz/',
        'https://www.chupacabrataproom.com/'
      ]
    },
    {
      id: 'crimewave-mesa',
      nightName: 'CRIMEWAVE (Mesa Edition)',
      theme: 'Goth / Industrial / Darkwave',
      venueName: 'Touring (Phoenix/Mesa)',
      address: 'Mesa (various venues)',
      city: 'Mesa',
      region: 'AZ',
      country: 'US',
      lat: 33.4152,
      lng: -111.8315,
      type: 'club-night',
      recurrence: 'Touring / Periodic',
      scheduleDetail: 'Touring goth/industrial night (dates/venues vary).',
      notes: 'CRIMEWAVE hosts periodic touring events in Mesa/Phoenix; check social for next event.',
      sources: [
        'https://www.instagram.com/crimewaveparty/'
      ]
    },
    {
      id: 'club-necromancy-starlet-sacramento',
      nightName: 'Club Necromancy',
      theme: 'Goth / Industrial / Darkwave',
      venueName: 'The Starlet Room',
      address: '2708 J St',
      city: 'Sacramento',
      region: 'CA',
      country: 'US',
      lat: 38.5726,
      lng: -121.4716,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly goth/industrial night (dates vary).',
      notes: 'Club Necromancy is Sacramento’s anchor goth/industrial night at The Starlet Room; check social for next event.',
      sources: [
        'https://www.instagram.com/clubnecromancy/',
        'https://www.thestarletroom.com/'
      ]
    },
    {
      id: 'club-absolution-starlet-sacramento',
      nightName: 'Club Absolution',
      theme: 'Goth / Industrial / Darkwave',
      venueName: 'The Starlet Room',
      address: '2708 J St',
      city: 'Sacramento',
      region: 'CA',
      country: 'US',
      lat: 38.5726,
      lng: -121.4716,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly goth/industrial night (dates vary).',
      notes: 'Club Absolution is a monthly goth/industrial night at The Starlet Room, Sacramento; check social for next event.',
      sources: [
        'https://www.instagram.com/clubabsolution/',
        'https://www.thestarletroom.com/'
      ]
    },
    {
      id: 'factor-x-goldfield-sacramento',
      nightName: 'Factor X',
      theme: 'Goth / Industrial / Darkwave',
      venueName: 'Goldfield Trading Post',
      address: '1630 J St',
      city: 'Sacramento',
      region: 'CA',
      country: 'US',
      lat: 38.5771,
      lng: -121.4842,
      type: 'club-night',
      recurrence: 'Periodic',
      scheduleDetail: 'Periodic goth/industrial night (dates vary).',
      notes: 'Factor X is a periodic goth/industrial night at Goldfield Trading Post, Sacramento; check social for next event.',
      sources: [
        'https://www.instagram.com/factorxsacramento/',
        'https://goldfieldtradingpost.com/'
      ]
    },
    {
      id: 'ascension-heretic-atlanta',
      nightName: 'Ascension',
      theme: 'Goth / Industrial / Darkwave',
      venueName: 'The Heretic',
      address: '2069 Cheshire Bridge Rd NE',
      city: 'Atlanta',
      region: 'GA',
      country: 'US',
      lat: 33.8116,
      lng: -84.3557,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly goth/industrial night (dates vary).',
      notes: 'Ascension is Atlanta’s anchor goth/industrial night at The Heretic; check social for next event.',
      sources: [
        'https://www.facebook.com/ascensionatl/',
        'https://www.hereticatlanta.com/'
      ]
    },
    {
      id: 'xmts-atlanta',
      nightName: 'Xmts Atlanta',
      theme: 'Goth / Industrial / Darkwave',
      venueName: 'The Heretic',
      address: '2069 Cheshire Bridge Rd NE',
      city: 'Atlanta',
      region: 'GA',
      country: 'US',
      lat: 33.8116,
      lng: -84.3557,
      type: 'club-night',
      recurrence: 'Periodic',
      scheduleDetail: 'Periodic goth/industrial night (dates vary).',
      notes: 'Xmts is a periodic goth/industrial night at The Heretic, Atlanta; check social for next event.',
      sources: [
        'https://www.facebook.com/xmtsatl/',
        'https://www.hereticatlanta.com/'
      ]
    },
    {
      id: 'afterlyfe-the-ship-kansas-city',
      nightName: 'AFTERLYFE',
      theme: 'Goth / Industrial / Darkwave',
      venueName: 'The Ship',
      address: '1221 Union Ave',
      city: 'Kansas City',
      region: 'MO',
      country: 'US',
      lat: 39.1042,
      lng: -94.6036,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly goth/industrial night (dates vary).',
      notes: 'AFTERLYFE is Kansas City’s anchor goth/industrial night at The Ship; check social for next event.',
      sources: [
        'https://www.facebook.com/afterlyfekc/',
        'https://www.theshipkc.com/'
      ]
    },
    {
      id: 'vampire-prom-truman-kansas-city',
      nightName: 'Vampire Prom',
      theme: 'Goth / Vampire / Darkwave Annual Ball',
      venueName: 'The Truman',
      address: '601 E Truman Rd',
      city: 'Kansas City',
      region: 'MO',
      country: 'US',
      lat: 39.0997,
      lng: -94.5736,
      type: 'festival',
      recurrence: 'Annual',
      scheduleDetail: 'Annual Vampire Prom ball (dates vary).',
      notes: 'Annual Vampire Prom ball at The Truman, Kansas City; check social for next event.',
      sources: [
        'https://www.facebook.com/vampirepromkc/',
        'https://www.thetrumankc.com/'
      ]
    },
    {
      id: 'goth-night-vultures-colorado-springs',
      nightName: 'Goth Night at Vultures',
      theme: 'Goth / Industrial / Darkwave',
      venueName: 'Vultures',
      address: '2100 E Platte Ave',
      city: 'Colorado Springs',
      region: 'CO',
      country: 'US',
      lat: 38.8451,
      lng: -104.7977,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly goth/industrial night (dates vary).',
      notes: 'Goth Night at Vultures is Colorado Springs’ anchor goth/industrial night; check social for next event.',
      sources: [
        'https://www.facebook.com/vulturescos/',
        'https://www.vulturesrocks.com/'
      ]
    },
    {
      id: 'vampire-ball-vultures-colorado-springs',
      nightName: 'Vampire Ball',
      theme: 'Goth / Vampire / Darkwave Annual Ball',
      venueName: 'Vultures',
      address: '2100 E Platte Ave',
      city: 'Colorado Springs',
      region: 'CO',
      country: 'US',
      lat: 38.8451,
      lng: -104.7977,
      type: 'festival',
      recurrence: 'Annual',
      scheduleDetail: 'Annual Vampire Ball (dates vary).',
      notes: 'Annual Vampire Ball at Vultures, Colorado Springs; check social for next event.',
      sources: [
        'https://www.facebook.com/vulturescos/',
        'https://www.vulturesrocks.com/'
      ]
    },
    {
      id: 'club-noir-down-under-omaha',
      nightName: 'Club Noir',
      theme: 'Goth / Industrial / Darkwave',
      venueName: 'The Down Under Lounge',
      address: '3530 Leavenworth St',
      city: 'Omaha',
      region: 'NE',
      country: 'US',
      lat: 41.2535,
      lng: -95.9721,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly goth/industrial night (dates vary).',
      notes: 'Club Noir is Omaha’s anchor goth/industrial night at The Down Under Lounge; check social for next event.',
      sources: [
        'https://www.facebook.com/clubnoiromaha/',
        'https://www.downunderomaha.com/'
      ]
    },
    {
      id: 'down-under-lounge-goth-night-omaha',
      nightName: 'Down Under Lounge Goth Night',
      theme: 'Goth / Industrial / Darkwave',
      venueName: 'The Down Under Lounge',
      address: '3530 Leavenworth St',
      city: 'Omaha',
      region: 'NE',
      country: 'US',
      lat: 41.2535,
      lng: -95.9721,
      type: 'club-night',
      recurrence: 'Monthly',
      scheduleDetail: 'Monthly goth/industrial night (dates vary).',
      notes: 'Down Under Lounge hosts recurring goth/industrial nights in Omaha; check social for next event.',
      sources: [
        'https://www.facebook.com/downunderomaha/',
        'https://www.downunderomaha.com/'
      ]
    }
];

// Utility: group nights by country/region/city (can be imported elsewhere if needed)
export function groupByLocation(data = nights) {
  const map = new Map();
  data.forEach(n => {
    const key = `${n.country}|${n.region}|${n.city}`;
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(n);
  });
  return Array.from(map.entries())
    .map(([k, list]) => {
      const [country, region, city] = k.split('|');
      return { country, region, city, nights: list.sort((a,b)=>a.nightName.localeCompare(b.nightName)) };
    })
    .sort((a,b)=> a.country.localeCompare(b.country) || a.region.localeCompare(b.region) || a.city.localeCompare(b.city));
}
